name: Testing Bootcamp 

on:
  push:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-tatest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run test-text